on: [push]

jobs:
  build_docs_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Dependencies
      run: |
        echo `python3 --version`
        sudo apt-get install -y python-setuptools
        sudo apt-get install -y python3-sphinx
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools
        python3 -m pip install -r requirements.txt
        python3 -m pip install ninja
        python3 -m pip install torch==1.8.1
        python3 -m pip install --pre onnxruntime-training -f https://onnxruntimepackages.z14.web.core.windows.net/onnxruntime_nightly_cu102.html
        python3 -m pip install torch-ort

      id: build
    - name: Build the docset
      run: |
        cd ./docs
        python3 -m pip install -r requirements.txt
        make html
        cd ..    
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: website/build # The folder the action should deploy. 
